namespace: vprofile
registry: vineeth2210
app:
  replicaCount: 2
  image:
    repository: vprofile-app
    tag: ""
cache:
  replicaCount: 2
  image:
    repository: memcached
    tag: ""
db:
  replicaCount: 1
  image:
    repository: vprofile-db
    tag: ""
  config:
    MYSQL_DATABASE: accounts
rabbitmq:
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: ""
web:
  replicaCount: 1
  image:
    repository: vprofile-web
    tag: ""
    
