apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vprofile-web
  name: vprofile-web
  namespace: vprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vprofile-web
    spec:
      containers:
      - image: vineeth2210/vprofile-web:latest
        name: vprofile-web
        ports:
        - containerPort: 80
        resources: {}
status: {}
