apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}{{ "-web" }}
  name: {{ .Chart.Name }}{{ "-web" }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}{{ "-web" }}
  type: NodePort
