apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}{{ "-db" }}
  name: vprodb
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: {{ .Chart.Name }}{{ "-db" }}
status:
  loadBalancer: {}
