apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}{{ "-memcached" }}
  name: vprocache01
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: {{ .Chart.Name }}{{ "-memcached" }}
