apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}{{ "-db-secret" }}
  namespace: {{ .Values.namespace }}
data:
  MYSQL_ROOT_PASSWORD: dnByb2RicGFzcw==
  MYSQL_USER: c3FsYWRtaW4K
  MYSQL_PASSWORD: c3FsYWRtaW4K