apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}{{ "-app" }}
  name: {{ .Chart.Name }}{{ "-app" }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.app}}
  replicas: {{ .replicaCount | default 1 }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ "-app" }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ "-app" }}
    spec:
      containers:
      - image: {{ include "app.image" . }}
        name: {{ .Chart.Name }}{{ "-app" }}
        ports:
        - containerPort: 8080
        resources: {}
