apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vprofile-rabbitmq
  name: vpromq01
  namespace: vprofile
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: vprofile-rabbitmq
status:
  loadBalancer: {}
