apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}{{ "-db" }}
  name: {{ .Chart.Name }}{{ "-db" }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.db }}
  replicas: {{ .replicaCount | default 1 }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ "-db" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.Name }}{{ "-db" }}
    spec:
      containers:
      - image: {{ include "db.image" . }}
        name: {{ .Chart.Name }}{{ "-db" }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: {{ .Chart.Name }}{{ "-db-secret" }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: {{ .Chart.Name }}{{ "-db-secret" }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: {{ .Chart.Name }}{{ "-db-secret" }}
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: {{ .Chart.Name }}{{ "-db-cm" }}
        resources: {}
status: {}
