apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}{{ "memcached" }}
  name: {{ .Chart.Name }}{{ "-memcached-svc" }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: {{ .Chart.Name }}{{ "memcached" }}
status:
  loadBalancer: {}
