apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}{{ "-web" }}
  name: {{ .Chart.Name }}{{ "-web" }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.web }}
  replicas: {{ .replicaCount | default 1 }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ "-web" }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ "-web" }}
    spec:
      containers:
      - image: vineeth2210/vprofile-web:latest
        name: {{ .Chart.Name }}{{ "-web" }}
        ports:
        - containerPort: 80
        resources: {}
