apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vprofile-web
  name: vproweb
  namespace: vprofile
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vprofile-web
  type: NodePort
status:
  loadBalancer: {}
