apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}{{ "-memcached" }}
  name: {{ .Chart.Name }}{{ "-memcached" }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.cache }}
  replicas: {{ .replicaCount | default 1 }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ "-memcached" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.Name }}{{ "-memcached" }}
    spec:
      containers:
      - image: {{ include "cache.image" . }}
        name: {{ .Chart.Name }}{{ "-memcached" }}
        ports:
        - containerPort: 11211
        resources: {}
status: {}
